export const Comments = [
  {
    id: '0',
    foodId: '0',
    rating: '5',
    comment: 'Nice!',
    author: 'Nitish Biswas',
    date: '2020-08-21',
  },
  {
    id: '1',
    foodId: '0',
    rating: '4.5',
    comment: 'WOW!',
    author: 'Tonmoy Baidya',
    date: '2020-08-22',
  },
  {
    id: '2',
    foodId: '0',
    rating: '5',
    comment: 'Amazing!',
    author: 'Niloy Biswas',
    date: '2020-08-22',
  },
  {
    id: '3',
    foodId: '1',
    rating: '5',
    comment: 'Nice!',
    author: 'Nitish Biswas',
    date: '2020-08-21',
  },
  {
    id: '4',
    foodId: '1',
    rating: '4.5',
    comment: 'WOW!',
    author: 'Tonmoy Baidya',
    date: '2020-08-22',
  },
  {
    id: '5',
    foodId: '2',
    rating: '5',
    comment: 'Amazing!',
    author: 'Niloy Biswas',
    date: '2020-08-22',
  },
  {
    id: '6',
    foodId: '2',
    rating: '5',
    comment: 'Nice!',
    author: 'Nitish Biswas',
    date: '2020-08-21',
  },
  {
    id: '7',
    foodId: '3',
    rating: '4.5',
    comment: 'WOW!',
    author: 'Tonmoy Baidya',
    date: '2020-08-22',
  },
  {
    id: '8',
    foodId: '3',
    rating: '5',
    comment: 'Amazing!',
    author: 'Niloy Biswas',
    date: '2020-08-22',
  },
  {
    id: '9',
    foodId: '4',
    rating: '5',
    comment: 'Nice!',
    author: 'Nitish Biswas',
    date: '2020-08-21',
  },
  {
    id: '10',
    foodId: '4',
    rating: '4.5',
    comment: 'WOW!',
    author: 'Tonmoy Baidya',
    date: '2020-08-22',
  },
  {
    id: '11',
    foodId: '5',
    rating: '5',
    comment: 'Amazing!',
    author: 'Niloy Biswas',
    date: '2020-08-22',
  },
];
